WeatherProject/force-app/main/default/objects/Weather_Data__c/Weather_Data__c.object-meta.xml
<CustomObject>
    <label>Weather Data</label>
    <nameField>
        <label>Weather Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Date_Time_of_Data_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_of_Data_Calculation__c</fullName>
    <description>Date Time of Data Calculation from Time of data calculation, unix, UTC</description>
    <label>Date Time of Data Calculation</label>
    <type>DateTime</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/dt__c.field-meta.xml
<CustomField>
    <fullName>dt__c</fullName>
    <description>Time of data calculation, unix, UTC</description>
    <label>dt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Main_Humidity__c.field-meta.xml
<CustomField>
    <fullName>Main_Humidity__c</fullName>
    <description>Humidity, %</description>
    <label>Main Humidity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Main_Temp__c.field-meta.xml
<CustomField>
    <fullName>Main_Temp__c</fullName>
    <description>Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.</description>
    <label>Main Temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Sys_Country__c.field-meta.xml
<CustomField>
    <fullName>Sys_Country__c</fullName>
    <description>Country code (GB, JP etc.)</description>
    <label>Sys Country</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Weather_Description__c.field-meta.xml
<CustomField>
    <fullName>Weather_Description__c</fullName>
    <description>Weather condition within the group. You can get the output in your language.</description>
    <label>Weather Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <description>Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour.</description>
    <label>Wind Speed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/classes/WeatherController.cls
public class WeatherController {

    @AuraEnabled
    public static string insertWeather(Weather_Data__c cwdToBeUpserted){
        try {
            List<Weather_Data__c> existingCwdList =  [SELECT Id FROM Weather_Data__c WHERE dt__c = :cwdToBeUpserted.dt__c AND Name = :cwdToBeUpserted.Name];
            if(existingCwdList.size()>0) {
                return existingCwdList[0].id;
            } else {
                insert cwdToBeUpserted;
                return cwdToBeUpserted.id;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Weather_Data__c> getHistoricalWeather(String cityName, Date fromDate, Date toDate){
        try {
            return [SELECT  Id, Name, Sys_Country__c, Dt__c, Date_Time_of_Data_Calculation__c, Main_Temp__c, Main_Humidity__c,Wind_Speed__c,Weather_Description__c
                    FROM    Weather_Data__c
                    WHERE   Name = :cityName AND
                            Date_Time_of_Data_Calculation__c >= :fromDate AND
                            Date_Time_of_Data_Calculation__c <= :toDate
                    LIMIT   1000];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}