WeatherProject/force-app/main/default/objects/Weather_Data__c/Weather_Data__c.object-meta.xml
<CustomObject>
    <label>Weather Data</label>
    <nameField>
        <label>Weather Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Date_Time_of_Data_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_of_Data_Calculation__c</fullName>
    <description>Date Time of Data Calculation from Time of data calculation, unix, UTC</description>
    <label>Date Time of Data Calculation</label>
    <type>DateTime</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/dt__c.field-meta.xml
<CustomField>
    <fullName>dt__c</fullName>
    <description>Time of data calculation, unix, UTC</description>
    <label>dt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Main_Humidity__c.field-meta.xml
<CustomField>
    <fullName>Main_Humidity__c</fullName>
    <description>Humidity, %</description>
    <label>Main Humidity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Main_Temp__c.field-meta.xml
<CustomField>
    <fullName>Main_Temp__c</fullName>
    <description>Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.</description>
    <label>Main Temp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Sys_Country__c.field-meta.xml
<CustomField>
    <fullName>Sys_Country__c</fullName>
    <description>Country code (GB, JP etc.)</description>
    <label>Sys Country</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <description>Shift in seconds from UTC</description>
    <label>Timezone</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Weather_Description__c.field-meta.xml
<CustomField>
    <fullName>Weather_Description__c</fullName>
    <description>Weather condition within the group. You can get the output in your language.</description>
    <label>Weather Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WeatherProject/force-app/main/default/objects/Weather_Data__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <description>Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour.</description>
    <label>Wind Speed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WeatherProject/force-app/main/default/classes/WeatherControllerTest.cls
@isTest
public class WeatherControllerTest {
    @isTest static void insertWeatherTest() {
        Weather_Data__c wd = new Weather_Data__c(Name='TestCity1', Date_Time_of_Data_Calculation__c=DateTime.now(), Main_Humidity__c=28, Main_Temp__c=80, Sys_Country__c='US', Timezone__c=-25200, Weather_Description__c='broken clouds', Wind_Speed__c=4, dt__c=1635199843);
        String wdid = WeatherController.insertWeather(wd);
        System.assertNotEquals(wdid, null,'Weather Data is not inserted');
        wdid = WeatherController.insertWeather(wd);
    }

    @isTest static void insertWeatherTestException() {
        Weather_Data__c wd = new Weather_Data__c(Date_Time_of_Data_Calculation__c=DateTime.now(), Main_Humidity__c=2822, Main_Temp__c=80, Sys_Country__c='US', Timezone__c=-25200, Weather_Description__c='broken clouds', Wind_Speed__c=4, dt__c=1635299843);
        try{
            String wdid = WeatherController.insertWeather(wd);
        } catch (Exception ex) {
            System.assertEquals('Script-thrown exception',ex.getMessage());
        }
    }

    @isTest static void getHistoricalWeatherTest() {
        Weather_Data__c wd = new Weather_Data__c(Name='TestCity2', Date_Time_of_Data_Calculation__c=DateTime.now(), Main_Humidity__c=28, Main_Temp__c=80, Sys_Country__c='US', Timezone__c=-25200, Weather_Description__c='broken clouds', Wind_Speed__c=4, dt__c=1635099843);
        insert wd;
        List<Weather_Data__c> hwd = WeatherController.getHistoricalWeather('TestCity2',null,null);
        System.assertEquals(1,hwd.size());        
    }
}